// SPDX-License-Identifier: GPL-2.0
// #include <bpf.h>
#include <vmlinux.h>
#include <bpf/bpf_helpers.h>
#include "common.h" // Skeleton header generated by bpftool
#include "common.maps.defs.h"

uint64_t message_monotonic_sequence_id = 0;


// struct {
//     __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
//     // __uint(key_size, sizeof(struct data_t));
//     // __uint(value_size, sizeof(struct data_t));
//     __uint(max_entries, 0);
// } events SEC(".maps");


BPF_PERF_OUTPUT(events, sizeof(u32), sizeof(u32))

SEC("tracepoint/syscalls/sys_enter_read")
int tracepoint_sys_enter_read(struct trace_event_raw_sys_enter *ctx) {
    struct data_t data = {};
    uint32_t pid = bpf_get_current_pid_tgid() >> 32;

    data.pid = pid;
    bpf_get_current_comm(&data.comm, sizeof(data.comm));

    char *buf = (char *)ctx->args[1];
    int bytes = (int)ctx->args[2];
    data.bytes = bytes > sizeof(data.data) ? sizeof(data.data) : bytes;

    // bpf_probe_read_user(data.data, data.bytes, buf);
    data.seq_id = __sync_add_and_fetch(&message_monotonic_sequence_id, 1);
    bpf_perf_event_output(ctx, &events, BPF_F_CURRENT_CPU, &data, sizeof(data));

    return 0;
}

SEC("tracepoint/syscalls/sys_enter_write")
int tracepoint_sys_enter_write(struct trace_event_raw_sys_enter *ctx) {
    struct data_t data = {};
    uint32_t pid = bpf_get_current_pid_tgid() >> 32;

    data.pid = pid;
    bpf_get_current_comm(&data.comm, sizeof(data.comm));

    char *buf = (char *)ctx->args[1];
    int bytes = (int)ctx->args[2];
    data.bytes = bytes > sizeof(data.data) ? sizeof(data.data) : bytes;

    // bpf_probe_read_user(data.data, data.bytes, buf);
    data.seq_id = __sync_add_and_fetch(&message_monotonic_sequence_id, 1);
    bpf_perf_event_output(ctx, &events, BPF_F_CURRENT_CPU, &data, sizeof(data));

    return 0;
}

char LICENSE[] SEC("license") = "GPL";
